### ISSUE TITLE
Latest version is 1.1.3 (atom packages)

### ISSUE THREAD

**Issue by mishak87** [jagregory/language-docker#14]
Latest version on [atom packages page](https://atom.io/packages/language-docker) is 1.1.3.
Maybe something went wrong with release process?

**Comment by jagregory** [comment]
Should be ok now. Not sure what happened. Thanks!

On Wed, Dec 2, 2015 at 10:54 PM, Michal Gebauer <notifications@github.com>
wrote:

> Latest version on atom packages page
> <https://atom.io/packages/language-docker> is 1.1.3.
> Maybe something went wrong with release process?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jagregory/language-docker/issues/14>.
>



-- 
James Gregory

Tel: 0411619513
Website: http://jagregory.com
Twitter: @jagregory <http://twitter.com/jagregory>
