### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by envygeeks** [jagregory/language-docker#5]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/opt/atom/share/atom/resources/app/src/package.js:541:9)
<unknown> (/opt/atom/share/atom/resources/app/src/package.js:188:43)
```

**Comment by jagregory** [comment]
A Pull Request would be appreciated for this.

**Comment by envygeeks** [comment]
It was already fixed by @kevinsawicki I was just reposting it to let you know to publish.

**Comment by jagregory** [comment]
Thanks, I've pushed a new version.
