### ISSUE TITLE
Change file match to any file with 'Dockerfile' in it

### ISSUE THREAD

**Issue by darrenhaken** [jagregory/language-docker#8]
When using multiple containers you'll end up with multiple Dockerfiles.
For example I have one named 'Dockerfile-nginx' which stops syntax highlighting.

It would be good to be able to use regex on the name match so it can support multiple files.

**Comment by k4nar** [comment]
This would be very great.

**Comment by jagregory** [comment]
Unfortunately, this is a limitation of Atom. The "fileType" association of a plugin is just a string, not a regex. :cry: 

You have two options:

  1. Rename your dockerfiles to `nginx.Dockerfile`
  2. Use the [file-types](https://atom.io/packages/file-types) extension to define your own regex pattern to use the Docker syntax highlighting
